### ISSUE TITLE
Update existing pull request

### ISSUE THREAD

**Issue by gr2m** [gr2m/octokit-plugin-create-pull-request#99]
I ran into this so often and always ended up implementing some workaround. But today is the day, I'll add an option like `update` that can be set to `true` and `false`. It will default to `false` to not break current behavior, but I think in future I'll default it to `true` instead because from my own experience that is the desired behavior.

**Comment by st3phhays** [comment]
I am using this feature, and am able to update the pull request title successfully, but if I pass in new files to be added to the PR, those files are not shown at all. I am not able to update existing files in the pull request either. Is this intentional, or is there another way to do this?

I am just getting started with octokit.js. Apologies if I'm missing something obvious!

**Comment by gr2m** [comment]
Definitely not intended, it should add new files when updating a pull request. Could you please create a new issue, ideally also sharing a minimal code example that reproduces the problem? I'll be happy to help

**Comment by st3phhays** [comment]
Thanks a lot! I created a new issue https://github.com/gr2m/octokit-plugin-create-pull-request/issues/107
